[workspace]
members = [ "glslt", "glslt_cli" ]

[patch.crates-io]
glsl-lang = { git = "https://github.com/vtavernier/glsl-lang" }
lang-util = { git = "https://github.com/vtavernier/glsl-lang" }
lang-util-derive = { git = "https://github.com/vtavernier/glsl-lang" }

glslt = { path = "glslt" }
