[workspace]
members = [ "glslt", "glslt_cli" ]

[patch.crates-io]
glsl-lang = { git = "https://github.com/vtavernier/glsl-lang" }
glsl-lang-impl = { git = "https://github.com/vtavernier/glsl-lang" }
glslt = { path = "glslt" }
