[workspace]
members = [ "glslt", "glslt_cli" ]

[patch.crates-io]
glsl = { git = "https://github.com/vtavernier/glsl", branch = "dev" }
glsl-impl = { git = "https://github.com/vtavernier/glsl", branch = "dev" }
glslt = { path = "glslt" }
