ignore_merge_commits = true
pre_bump_hooks = [
  "./ci/bumpver.sh {{version}}",
  "git add Cargo.lock */Cargo.toml",
]
post_bump_hooks = [
  "git commit --amend --no-edit -m \"chore(version): v{{version}} [skip ci]\""
]
tag_prefix = "v"

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = [
  { signature = "Vincent Tavernier", username = "vtavernier" }
]

[bump_profiles]
