name: apply-version-bundle
description: Apply a version bundle contained in a release artifact
inputs:
  new_release:
    description: Was a new release created
  version:
    description: Git tag of the created release
  bundle_file:
    description: Path to the bundle file in the artifact
  artifact_name:
    description: Artifact name to retrieve
runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
      if: inputs.new_release == 'true'

    - run: |
        git pull ${{ inputs.bundle_file }} HEAD:$(git rev-parse --abbrev-ref HEAD)
        git tag ${{ inputs.version }}
      shell: bash
      if: inputs.new_release == 'true'

